"""Microchips updated

Revision ID: 5a80b4938daf
Revises: ddbcfc0ade91
Create Date: 2024-10-27 15:45:05.248862

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a80b4938daf'
down_revision = 'ddbcfc0ade91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('microchips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=False))

    with op.batch_alter_table('uploaded_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('successful', sa.Boolean(), nullable=False))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('successful')

    with op.batch_alter_table('microchips', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
